# Generated by Django 3.2.25 on 2026-05-01 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_visit', models.PositiveIntegerField(default=0)),
                ('desktop_visit', models.PositiveIntegerField(default=0)),
                ('mobile_visit', models.PositiveIntegerField(default=0)),
                ('other_devices_visit', models.PositiveIntegerField(default=0)),
                ('chrome_visit', models.PositiveIntegerField(default=0)),
                ('firefox_visit', models.PositiveIntegerField(default=0)),
                ('other_explorers_visit', models.PositiveIntegerField(default=0)),
                ('unique_visitor', models.PositiveIntegerField(default=0)),
                ('unique_desktop_visitor', models.PositiveIntegerField(default=0)),
                ('unique_mobile_visitor', models.PositiveIntegerField(default=0)),
                ('unique_other_devices_visitor', models.PositiveIntegerField(default=0)),
                ('unique_chrome_visitor', models.PositiveIntegerField(default=0)),
                ('unique_firefox_visitor', models.PositiveIntegerField(default=0)),
                ('unique_other_explorers_visitor', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'analytics',
                'verbose_name_plural': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('url', models.URLField(default='')),
                ('shorten_url', models.URLField(default='')),
                ('hash', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'url',
                'verbose_name_plural': 'urls',
                'index_together': {('creator', 'uuid')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(default='', max_length=100)),
                ('visitor_ip', models.GenericIPAddressField()),
                ('visitor_device', models.CharField(default='', max_length=30)),
                ('visitor_browser', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='UrlShortener_urls.url')),
            ],
            options={
                'verbose_name': 'visit',
                'verbose_name_plural': 'visits',
            },
        ),
    ]
